version: '3.3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    env_file: ../.env
    build: ../backend/
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    env_file: ../.env
    build: ../frontend/
    command: cp -r /app/build/. /static/
    depends_on:
      - db
    volumes:
      - static:/static
  infra:
    build: .
    env_file: ../.env
    ports:
      - 8090:90
    volumes:
      - static:/staticfiles/
      - media:/app/media/
